<?php if(isset($form)): ?>
<div class="jumbotron">
	<h1>Nouvel evenement</h1>
	<?php 
$form->setAttribute('action', $this->url('gestproposition', array('action'=>'add', 'id' => $form->getInputFilter()->getValue('idevenement'),)));
		$form->setAttribute('class', 'form-horizontal');
		$form->prepare();
		
		echo $this->form()->openTag($form);
		
		echo $this->formHidden($form->get('idevenement'));
		echo $this->formHidden($form->get('nbpartmax'));
	?>
	
	<div class="control-groupe-col-sm-3">
		<?php echo $this->formLabel($form->get('titre')); ?>
	</div>
	<div class="control-group-col-sm-9">
		<?php echo $this->formInput($form->get('titre')); ?>
	</div>
	
	<div class="control-groupe-col-sm-3">
		<?php echo $this->formLabel($form->get('description_resume')); ?>
	</div>
	<div class="control-group-col-sm-9">
		<?php echo $this->formInput($form->get('description_resume')); ?>
	</div>
	
	<div class="control-groupe-col-sm-3">
		<?php echo $this->formLabel($form->get('date_debut')); ?>
	</div>
	<div class="control-group-col-sm-9">
		<?php echo $this->formInput($form->get('date_debut')); ?>
	</div>
	
	<div class="control-groupe-col-sm-3">
		<?php echo $this->formLabel($form->get('date_fin')); ?>
	</div>
	<div class="control-group-col-sm-9">
		<?php echo $this->formInput($form->get('date_fin')); ?>
	</div>	
	
	<div class="control-groupe-col-sm-3">
		<?php echo $this->formLabel($form->get('adresse')); ?>
	</div>
	<div class="control-group-col-sm-9">
		<?php echo $this->formInput($form->get('adresse')); ?>
	</div>
	
	</br>
	
	<?php echo $this->formSubmit($form->get('submit')); ?>
	
	<?php echo $this->form()->closeTag(); ?>
</div>
<?php else: ?>

<?php endif ?>