<div class="jumbotron">
    <h1>Evenements</h1>
    <table class="table">
        <tr>
            <th>Titre</th>
            <th>Description</th>
            <th>Status</th>
            <th></th>
        </tr>
        <?php foreach($evenements as $ev) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($ev->titre); ?></td>
            <td><?php echo $this->escapeHtml($ev->description_resume); ?></td>
            <td><?php echo $this->escapeHtml($ev->status); ?></td>
            <td class="pull-right"><a class="btn btn-success" href="<?php echo $this->url('gestevenement', array('action'=>'detail', 'id' => $ev->idevenement)); ?>" target=""><?php echo $this->translate('Détails') ?> &raquo;</a>
            <a class="btn btn-success" href="<?php echo $this->url('gestevenement', array('action'=>'edit', 'id' => $ev->idevenement)); ?>" target=""><?php echo $this->translate('Modifier') ?> &raquo;</a></td>
        </tr>
            <?php endforeach; ?>
    </table>
</div>